#!/bin/bash

if [ ! "$(docker ps -q -f name=nginx)" ]; then
    if [ "$(docker ps -aq -f status=exited -f name=nginx)" ]; then
        # cleanup
        docker rm nginx
    fi
    # run your container
    docker run --name nginx -d -p 8080:80 nginx
fi
docker ps
docker exec -it nginx bash
